### ISSUE TITLE
Sending events from Stream to Unreal

### ISSUE THREAD

**Issue by Noah670** [markolofsen/metaeditor#1]
Is there a way to emit events to Unreal similar to the official version of Pixel streaming

This is listed in the documentation however the emit function does not seem to be working

```
`refPixelStreaming.current.emit({
 type: 'string', //key of command
 value: 0, //string, bool, number
 verification_id: undefined, //server response with execute command by verification id
})`
```

**Comment by markolofsen** [comment]
Right way:

```javascript
/**
 * Note that the Demo() function must be a child of the MetaEditor component.
 * <MetaEditor {{...}}>
 *    <Demo />
 * </MetaEditor>
 */
import Button from '@mui/material/Button';
import { usePlayer } from 'components/MetaEditor/context/'

function Demo() {
  const player = usePlayer()

  const handleCommand = (type, value, verification_id = null) => event => {
    player.cmd._emit(type, value, verification_id)
  }

  return (
    <Button onClick={handleCommand('demo_command', { anyObject: [.1, 3.14] })}>
      Send command to Unreal Engine
    </Button>
  )
}
```

**Comment by markolofsen** [comment]
[How to send command into PixelStreaming](https://metaeditor.io/docs/metaeditor/methods/commands)

**Comment by jjohnson5253** [comment]
Is it possible to just send a string instead of a JSON object with a verification type and initiator in the message? This is what I see: 
![image](https://user-images.githubusercontent.com/17039257/162078103-f220d20f-28a8-4036-a0c8-0f7dd216d8e4.png)

**Comment by markolofsen** [comment]
@jjohnson5253 Sending data as a string is a bad way. One of these days we will publish a plugin for Unreal Engine, please wait.

**Comment by markolofsen** [comment]
> @markolofsen How would you suggest sending data then? As JSON?

Check out are here 
https://metaeditor.io/docs/metaeditor/methods/commands

**Comment by jjohnson5253** [comment]
> > @markolofsen How would you suggest sending data then? As JSON?
> 
> Check out are here https://metaeditor.io/docs/metaeditor/methods/commands

So just JSON?
