### ISSUE TITLE
Unable to add new project

### ISSUE THREAD

**Issue by wannabeanimated** [markolofsen/metaeditor#10]
Hello,

I would like to try the meta editor pixel streaming service but I am unable to upload my unreal file.
The new project button is greyed out even after creating a free account. Is there something I have to do to have access to that capability?

![Screenshot 2022-08-08 162709](https://user-images.githubusercontent.com/107233971/183508327-28d022fa-6c7f-45cb-b615-eed3453f1892.png)

**Comment by markolofsen** [comment]
@wannabeanimated 
We have temporarily closed the portal for publishing your projects. We apologise. We promise to release a new version soon!
