### ISSUE TITLE
Could be MetaClient open source?

### ISSUE THREAD

**Issue by marospekarik** [markolofsen/metaeditor#13]
Hi, @markolofsen, thanks for this work, the project looks interesting. I am trying to run the MetaEditor for my hobby project and missing MetaClient. Where can I find it? Thanks!

**Comment by markolofsen** [comment]
@marospekarik 
Hello! Thanks for the feedback!
We have released a new version of [pixel-streaming for Unreal Engine 5.2](https://www.npmjs.com/package/pixel-streaming).
Now it's even easier to get started.
