### ISSUE TITLE
How to Override MetaEditor Tag Style

### ISSUE THREAD

**Issue by hadi-ilies** [markolofsen/metaeditor#26]
Hi !
I hope you're doing well !
I'm using your Package, but I'm not able to change/disable full-screen mode on MetaEditor Tag Even when I try to change the style directly through CSS 
Do you have any idea how I can fix this issue ?

Br.

**Comment by hadi-ilies** [comment]
the 4.2.3 !

**Comment by markolofsen** [comment]
@hadi-ilies 

You can set the showToolbar={false} parameter in this case, all buttons will simply disappear.

**Comment by markolofsen** [comment]
@hadi-ilies 
The fact is that the technology is created so that the video closes the entire screen.
But if you want to register the size for tag with the video, you can do it for example
`document.getElementById('streamingVideo').style.top = '10rem'`

**Comment by hadi-ilies** [comment]
Okay, I did it !
I just changed the style of the ids and classes from the global index.css (reactjs) and I added `!important` in order to override your CSS 

thank you for your help :)

**Comment by markolofsen** [comment]
Nice!)
