### ISSUE TITLE
How to use MetaEditor Pixel-Streaming in react 17.0.2?

### ISSUE THREAD

**Issue by jhonatan-dev** [markolofsen/metaeditor#34]
Hi,
Thanks for this great MetaEditor, Pixel-streaming. I am gonna insert Unreal player in React 17.0.2 project.
Please let me know how to insert for my project.

**Comment by markolofsen** [comment]
Better to use our read-made project with React 18* and Nextjs. It's already configured.
```
# 1. clone repo
git clone https://github.com/markolofsen/metaeditor.git

# 2. Installation
cd ./metaeditor
yarn && yarn dev

# 3. open http://localhost:3000
```
