### ISSUE TITLE
Stream is not active. Can not emit UI interaction.

### ISSUE THREAD

**Issue by hadi-ilies** [markolofsen/metaeditor#38]
Hi !
I'm trying to interact with my UE5 project from the html. Unfortunately, I have an error when I call `emitUi` function 

Here is the error:
* Stream is not active. Can not emit UI interaction.

Where can I enable the Stream ?  

PS: I have all my UE5 project and pixel streaming server running, and I'm able to run/play my game from my React app

**Comment by markolofsen** [comment]
@hadi-ilies 
Please provide a link to the repository with your project
