### ISSUE TITLE
The mouse is not aligned correctly

### ISSUE THREAD

**Issue by aaronmack** [markolofsen/metaeditor#6]
The mouse does not align correctly in **pixel-streaming**, which makes some operations, such as moving the axis of rotation difficult. Is there any way to align it correctly? 

It's true in the middle, it's cheaper as you go around.

![Mouse](https://user-images.githubusercontent.com/43235864/164625312-dc4aaa56-6544-4246-9cee-8ffe10824654.gif)
 
Any help would be greatly appreciated.

**Comment by AAaronMack** [comment]
If I set the resolution of the Unreal `pixel streaming` to the same as the browser resolution, I can get the correct result, what else can I do?  Especially zoom in on the browser

**Comment by markolofsen** [comment]
@AAaronMack 

Try to update pixel streaming module.
```bash
yarn add pixel-streaming@^2.3.8
```
Make changes [from the documentation](https://metaeditor.io/docs/pixel-streaming/settings)

**Comment by aaronmack** [comment]
I set `connectOnStart: true` and the `pixel streaming` disappears, I am using React v17.0.2

**Comment by markolofsen** [comment]
@aaronmack 2.3.9 =)

**Comment by aaronmack** [comment]
![image](https://user-images.githubusercontent.com/43235864/165320594-fb63dee4-bb08-425a-b4d0-d0c5fcda4344.png)

Still doesn't seem to work correctly and gets some errors.

**Comment by markolofsen** [comment]
@aaronmack 
Please provide a link to your repo =)

**Comment by aaronmack** [comment]
> 

https://github.com/WinsingAaron/my-app    I didn't succeed in this simple project

**Comment by aaronmack** [comment]
> > 
> 
> https://github.com/WinsingAaron/my-app I didn't succeed in this simple project

Where `src/Player.js` is pixel Streaming

**Comment by markolofsen** [comment]
@aaronmack 
`yarn add pixel-streaming@^2.4.1`
`refPixelStreaming.current.connector.initConnection()`

**Comment by aaronmack** [comment]
If I set `connectOnStart: true`, I  will get some same errors as before. If I set `connectOnStart: false`, and make a button to call `refPixelStreaming.current.connector.initConnection()` when clicked. I can get the pictures from Pixel Streaming, But the mouse seems even more incorrect.

**Comment by markolofsen** [comment]
@aaronmack 
Looks like you haven't updated the version to 2.4.1
Mouse positioning should work. At startup, we send console commands to Unreal Engine:
```javascript
client.emitConsole(`PixelStreaming.Capturer.UseBackBufferSize 0`)
client.emitConsole(`PixelStreaming.Capturer.CaptureSize ${width}x${height}`)
client.emitConsole(`r.SetRes ${width}x${height}f`)
```

**Comment by aaronmack** [comment]
I updated it to 2.4.3. and using the `emitConsole` method, and got some errors.

![image](https://user-images.githubusercontent.com/43235864/165451930-c8c4e750-d7a0-4a8f-a332-c2226847632b.png)

```javascript
import React, {useEffect} from "react";

// libs
import PixelStreaming, { usePS, DebugData } from 'pixel-streaming'

export default function Player(props) {
    const refPixelStreaming = React.useRef(null);
    const PS = usePS();


    const handleConnection = () => {
        refPixelStreaming.current.connector.initConnection()
    }

    useEffect(() => {
        window.addEventListener('resize', handleResize);
    }, []);

    const handleResize = () => {
        console.log('resized to ', window.innerWidth, 'x', window.innerHeight)

        const width = window.innerWidth
        const height = window.innerHeight

        //const emitConsole = refPixelStreaming.current.cls.client.emitConsole
        const emitConsole = PS.cls.client.emitConsole

        emitConsole(`PixelStreaming.Capturer.UseBackBufferSize 0`)
        emitConsole(`PixelStreaming.Capturer.CaptureSize ${width}x${height}`)
        emitConsole(`r.SetRes ${width}x${height}f`)
    }

    return (
        <div>
            <button onClick={handleConnection}>Connect</button>
            <PixelStreaming
                ref={refPixelStreaming}
                onLoad={(payload) => {
                    // console.warn('loaded', payload);
                }}
                onConnect={() => {
                    // console.warn('connected');
                }}
                onRestart={() => {
                    // console.warn('onRestart');
                }}
                onError={(payload) => {
                    // console.error('error', payload);
                }}
                onClose={(payload) => {
                    // console.error('closed', payload);
                }}
                onProgress={(payload) => {
                    // console.warn('progress', payload);
                }}
                settings={{
                    volume: 1,
                    quality: 1,
                    connectOnStart: false,

                    host: 'http://127.0.0.1',
                    port: 80,

                    pixelStreaming: {
                        warnTimeout: 120,
                        closeTimeout: 10,
                        lockMouse: false,
                        fakeMouseWithTouches: false,
                    }
                }}
                metaSettings={{
                    isDev: true,
                    showDevTools: true,
                    notifyCommands: true,
                    notifyCallbacks: true,
                }}
            >
                {(payload) => <div style={{ padding: 30 }}>{props.children}</div>}
            </PixelStreaming>
        </div>
    );
}
```

I used both methods `refPixelStreaming` and `PS`, but I seem to get the same error.

https://github.com/WinsingAaron/my-app    I updated this repository.

**Comment by markolofsen** [comment]
@aaronmack 
v2.4.4
Try `player.cls.setConnection({ host, port })`
=)

**Comment by WinsingAaron** [comment]
Like this? 
![image](https://user-images.githubusercontent.com/56584846/165486303-df48d796-3dd5-4c17-bbe4-722630f4b0b1.png)

But it still seems to be the wrong result.

![image](https://user-images.githubusercontent.com/56584846/165486416-a7556d0d-d5f1-4ded-b3d6-b0aad99b5d0c.png)

**Comment by aaronmack** [comment]
> @aaronmack I need time for investigation.

Be deeply grateful.

**Comment by markolofsen** [comment]
@aaronmack 
I tried implement this methods in your repo and that works!
pixel-streaming 2.4.5

```
const handleConnection = () => {
        refPixelStreaming.current.cls.initConnection({
            host: 'http://127.0.0.1',
            port: 80,
        })
    }
```

**Comment by aaronmack** [comment]
![Issuse](https://user-images.githubusercontent.com/43235864/165660985-5b7ae380-b156-4205-b8e6-864c4d14d0a4.gif)

It is ok to add `-ResX` and `-ResY` parameters that is consistent with the browser resolution when starting Unreal, like this.

![image](https://user-images.githubusercontent.com/43235864/165661776-4da3bcef-f1e5-4c49-b9f5-f5950122ede5.png)
e.g. `-ResX=601 -ResY=496`


but when the browser size changes, The position deviation of the mouse is very serious.

```javascript
    const handleResize = () => {
        console.log('resized to ', window.innerWidth, 'x', window.innerHeight)

        const width = window.innerWidth
        const height = window.innerHeight

        //const emitConsole = refPixelStreaming.current.cls.client.emitConsole
        const emitConsole = PS.cls.client.emitConsole

        emitConsole(`PixelStreaming.Capturer.UseBackBufferSize 0`)
        emitConsole(`PixelStreaming.Capturer.CaptureSize ${width}x${height}`)
        emitConsole(`r.SetRes ${width}x${height}f`)
    }
```

and I tried `handleResize`, but got an error, it doesn't seem to work properly.

I tried one solution, which was to get the browser resolution each time and then start Unreal as a parameter, but required the user not to enlarge or decrease the size of the browser. 

But they may change the size without knowing it.

**Comment by markolofsen** [comment]
@aaronmack works?

**Comment by markolofsen** [comment]
@aaronmack 
try `const emitConsole = (payload) => refPixelStreaming.current.cls.client.emitConsole(payload)`
