### ISSUE TITLE
Is source available?

### ISSUE THREAD

**Issue by smolgumball** [markolofsen/metaeditor#9]
Is source code available for the underlying `unreal-pixel-streaming` package? I'm interested in the product, but am less comfortable including obfuscated code without open source access in my project. 

The [NPM repository](https://www.npmjs.com/package/unreal-pixel-streaming) seems to be maintained by someone other than yourself, and I can't find any repository links on npm?

**Comment by markolofsen** [comment]
@smolgumball You can modify the source code of MetaEditor yourself. Try contacting the author of the `unreal-pixel-streaming` library yourself.

**Comment by smolgumball** [comment]
Hi @markolofsen, it looks like the only user of `unreal-pixel-streaming` is your product, so I'm a bit confused. Are you not in contact with the maintainer? 

Looking through the npm package history, it also seems as though `unreal-pixel-streaming` version `1.0.3` [references metaeditor.io directly](https://www.runpkg.com/?unreal-pixel-streaming@1.0.3/src/Custom/config.js).

Just to be clear, I was hoping to bring metaeditor.io into a large project at work, and to speak with your accounts team about an enterprise hosting plan and so forth, but I first needed to do some due diligence on the technology used.

Thus far, I am feeling fairly uncomfortable with what appears to be an attempt to intentionally mislead me? Could you clarify?
